### ISSUE TITLE
Does your website generator still work and do you still recommend and support it?

### ISSUE THREAD

**Issue by StefanSalewski** [h3rald/hastysite#8]
Dear Sir,

I am currently looking for a way to present my Nim book a bit better, https://nimprogrammingbook.com/ is really not that great. I built by own homepage fully manually 20 years ago, see ssalewski.de. I need only a very simple static site. But it should support desktop and mobil, which is hard by manually coding. A page created by GPT-4 may be an option, but I also consider Hugo or Jekyll. I just found your generator, and your Min homepage is already similar to my wishes. So the question is: Is this project still alive, and should I try or better avoid it. Does it even compile with recent Nim 1.9.3?

Best regards,

Dr. Stefan Salewski

**Comment by h3rald** [comment]
Hello,

Thank you for your interest in HastySite. I am still maintaining the project although not planning to add more features... I use it to run all my web sites and I am trying to make sure everything works but I do not have a lot of time due to work and family commitments.

It does compile on v1.6.12, but I haven't tried on non-stable versions.

**Comment by StefanSalewski** [comment]
Thanks for the fast reply. So it is the same as for many other Nim projects :-) I think I will try to learn some Jekill first, may be useful for other things as well.

Best regards, Stefan Salewski
